<section class="footer">
 
  <div class="footer-link">
      <p><a href="mailto:contact@3wa.fr">Opportunités</a></p>
      <p><a href="mailto:contact@3wa.fr">Opportunités</a></p>
      <p>©2022 Labelle Sites</p>
  </div>
  
  <div class="footer-contact">
    <img src="/Montessori/public/assets/images/logo/montessori_puzzle_color_bg_transparent_LR.png" alt="puzzle icon"></img>
    <h3>Montessori Les Loulous Futés</h3>
    <p>30 rue du chapeau rouge</p>
    <p>33 000 Bordeaux</p>
    <p><span class="zero-un">[ANTISPAM]</span> 02 03 04 05</p>

    <p>
      <a href="mailto:contact(arobase)3wa.fr">
	    contact<span class="arobase"><span>(arobase)</span></span>3wa.fr
      </a>
    </p>
  
  </div>
  

  <div class="footer-newsletter">
   <form>
    <label for="newsletter" class="newsletter"></label>
    <input type="text" placeholder="Votre adresse mail" name="newsletter" id="newsletter"/>
   </form>
   
  </div>

</section> 