<?php

$categoryList = "";

foreach($params["categoryList"] as $key=>$value) 
  {
    $categoryList .= "<option value=".$value->getId()." > ".utf8_encode($value->getName())."</option>";
  }
  
  //recuperate article, then if not empty, the values to inject in form
?>

  <form method="POST" enctype="multipart/form-data" class="user_add_form">

        <label for="article_title" class="article">Titre</label>
        <input type="text" value = "<?php echo (isset($prenomError))?$prenomError:'';?>" name="article_title" id="article_title" size="40" />

        <label for="article_categories" class="categories_add_form_label">Catégories</label>
        <select name="article_categories[]" multiple="multiple">
            <?php
                echo $categoryList;
            ?>
        </select>

        <label for="article_content" class="article_add_form_label">Contenu</label>
        <input type="textarea" name="article_content" id="article_content" size="40" />
        
        <label for="article_image">Télécharger une image:</label>
        <input type="file" id="article_image" name="article_image" accept="image/png, image/jpeg">
  
        <input type="submit" name="submit" value="Envoyer" />
        
    </form>
    