<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Confirmation</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Validez-vous la suppression de cet article ?</p>
        <p>Une fois l'article supprimée, elle n'est pas récupérable.</p>
      </div>
      <div class="modal-footer">

        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>

        <form method="GET">
          <input type="hidden" name="page" value="article_deleted"/>
          <input type="hidden" class="article-id" id="js_article_deleted_id" name="article_id"/>
          <input type="submit" class="btn btn-primary delete-article-btn" value="Supprimer"/>
                    
        </form>

      </div>
    </div>
  </div>
</div>
