<form method="POST" style="width:40%; margin-top:50px; margin-left:auto; margin-right: auto; align-self:center">
  <!-- Email input -->
  <div class="form-outline mb-4">
    <input type="text" id="username" name="username" class="form-control" />
    <label class="form-label" for="username">User Name</label>
  </div>

  <!-- Password input -->
  <div class="form-outline mb-4">
    <input type="password" id="password" name="password" class="form-control" />
    <label class="form-label" for="password">Password</label>
  </div>

  <!-- 2 column grid layout for inline styling -->
  <div class="row mb-4">
    <div class="col d-flex justify-content-center">
      <!-- Checkbox -->
      <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="remember" checked />
        <label class="form-check-label" for="remember"> Remember me </label>
      </div>
    </div>

    <div class="col">
      <!-- Simple link -->
      <a href="#!">Forgot password?</a>
    </div>
  </div>

  <!-- Submit button 
  <button type="button" class="btn btn-primary btn-block mb-4" name="sign_in">Sign in</button>
  -->
  <input type="submit" name="submit" class="btn btn-primary btn-block mb-4"value="Envoyer" />
  

  <!-- Register buttons -->
  <div class="text-center">
    <p>Not a member? <a href="#!">Register</a></p>
  </div>
</form>