<section class="login-card">
    
  <img src="/Montessori/public/assets/images/icon/login_icon.png" alt="login icon"></img>
  
  <form method="POST">
      
    <div class="form-input">  
      <label for="username" class="login-label"></label>
      <input type="text" placeholder="Username" name="username" id="username"/>
    </div>
    
    <div class="form-input">
      <label for="password" class="login-label"></label>
      <input type="text" placeholder="Mot de passe" name="password" id="password"/>
    </div>

    <div class="option-password">
      <a href="mailto:francesca.nadel@3wa.io">Mot de passe oublié?</a>
    </div>

    <button type="submit" class="btn" id="login-submit">Se Connecter</button>
        
    <div class="text-center">
      <p>L'accès a cet espace nécessite une inscription par la direction. 
      <a href="mailto:francesca.nadel@3wa.io">Demandez votre inscription 
      <strong style="color:var(--secondary)">ICI</strong></a>
    </div>

  </form>
    
</section>