<section class="account-banner"></section>


<section class="account-parent-name">
  <h2>Bonjour <?= utf8_encode($user->getFirstname()); ?> !</h2>
</section>

<section class="account-child-list">
  
  <?php foreach($children as $key => $child): ?>
    
    <a href="index.php?page=parent_class_feed&student-id=<?= $child->getId() ?>&class-id=<?= $child->getClassroom()->getId() ?>">
      <img class="account-child-img" src="<?= $child->getFilePathImage() ?>" alt="child avatar"></img>
      <h3> <?= $child->getFirstname() ?></h3>
      <p> <?= utf8_encode($child->getClassroom()->getName()) ?></p>
    </a>

  <?php endforeach; ?>

</section>