  <form method="POST" class="user_add_form">

        <label for="user_firstname" class="user_add_form_label">Prénom</label>
        <input type="text" value = "<?php echo (isset($prenomError))?$prenomError:'';?>" name="user_firstname" id="user_firstname" size="40" />

        <label for="user_lastname" class="user_add_form_label">Nom</label>
        <input type="text" value = "<?php echo (isset($nomError))?$nomError:'';?>" name="user_lastname" id="user_lastname" size="40" />

        <label for="user_username" class="user_add_form_label">Username</label>
        <input type="text" value = "<?php echo (isset($usernameError))?$usernameError:'';?>" name="user_username" id="user_username" size="40" />

        <label for="user_password" class="user_add_form_label">Password</label>
        <input type="text" value = "<?php echo (isset($passwordError))?$passwordError:'';?>" name="user_password" id="user_password" size="40" />

        <input type="submit" name="submit" value="Envoyer" />
        
    </form>
    