<?php require_once dirname(__DIR__, 2) . "/src/Repository/CommentRepository.php"; ?>

<?php

  if(isset($_SESSION['login']) && ($_SESSION['user_role']=="parent"))
  {
    
    
    
  }
?>


        
<section class="class-feed">
  
  <!-- loop through all the posts available -->
  <?php 
  

    foreach($allRelatedFeeds as $key => $feed): ?>
        
    <div class="feed-post">
        <img class="class-feed-image" src="<?= $feed->getFilePathImage() ?>" alt="<?= $feed->getImageDescription() ?>"></img>
        <p class="post-date"> <?= $feed->getPublishDate() ?></p>
        <p> <?= $feed->getContent() ?></p>

          

        <!-- loop through all the comments available -->
        <?php $allRelatedComments = $feed->getCommentsOfFeed();
          // recupère tous les comments qui n'ont pas de commentaire parent

            if( $allRelatedComments){
                require dirname(__DIR__) . "/feed/template_part/__feed_comment.phtml"; 
            }
        ?>
        
    </div>
    
  <?php endforeach; ?>
  
</section>