<section id="home-carousel">
  
  


  <div class="carousel-item active" id="1"> 
    <img src="/Montessori/public/assets/images/classroom_student/front_view_children_playing_together.jpg" alt="...">
    <div class="carousel-caption">
      <h5>L'importance de sociabiliser</h5>
      <p>L’école Les Loulous considère que pour un apprentissage constructif et enrichissant, les expériences actives menées 
      par l’enfant doivent avoir lieu dans un environnement adapté. 
      C’est en respectant le rythme de l’enfant, dans un cadre naturel et bienveillant que l’éveil sera le plus propice. </p>
    </div>
  </div>
  
  <div class="carousel-item" id="2"> 
    <img src="/Montessori/public/assets/images/classroom_student/front_view_children_exercise_hands_up_p_danilyuk.jpg" alt="...">
      <div class="carousel-caption">
      <h5>Learn how to move it!</h5>
      <p>Pour accompagner vos enfants dans leur développement au cours de ces années si cruciales, 
      l’école Les Étoiles respecte les “critères” de la méthode Montessori.</p>
    </div>
  </div>
  
  <div class="carousel-item" id="3"> 
    <img src="/Montessori/public/assets/images/courtyard/back_view_children_observe_nature_e_bolovtsova.jpg" alt="...">
      <div class="carousel-caption">
      <h5>La nature</h5>
      <p>L’action pédagogique d’apprentissage dans et par la nature est dominée par les cycles de celle-ci 
      ainsi que par les propres intérêts de l’enfant.</p>
    </div>
  </div>
  
  <div class="carousel-buttons">
    <button class="carousel-previous" type="button">
      <img src="/Montessori/public/assets/images/icon/carousel_previous_icon.png"></img>
    </button>
    
    <button class="carousel-next" type="button">
       <img src="/Montessori/public/assets/images/icon/carousel_next_icon.png"></img>
    </button>
  </div>

</section>
