<div id="home-carousel">
  <!-- carousel item 1 -->
  <div class="carousel-item active" id="1"> 
    <img title="©Y. Krukov" src="/Montessori/public/assets/images/classroom_student/front_view_children_playing_together_y_krukov.jpg" alt="children playing together on the floor">
    <div class="carousel-caption">
      <h5>L'importance de sociabiliser</h5>
      <p>L’école Les Loulous considère que pour un apprentissage constructif et enrichissant, les expériences actives menées 
      par l’enfant doivent avoir lieu dans un environnement adapté.</p>
    </div>
  </div>
  
  <!-- carousel item 2 -->
  <div class="carousel-item" id="2"> 
    <img title="©P. Danilyuk" src="/Montessori/public/assets/images/classroom_student/front_view_children_exercise_hands_up_p_danilyuk.jpg" alt="young children exercising in a classroom">
      <div class="carousel-caption">
      <h5>Learn how to move it!</h5>
      <p>Pour accompagner vos enfants dans leur développement au cours de ces années si cruciales, 
      l’école Les Étoiles respecte les “critères” de la méthode Montessori.</p>
    </div>
  </div>
  
  <!-- carousel item 3 -->
  <div class="carousel-item" id="3"> 
    <img title="©E. Bolovtsova" src="/Montessori/public/assets/images/courtyard/back_view_children_observe_nature_e_bolovtsova.jpg" alt="2 children observing nature with a looking glass">
      <div class="carousel-caption">
      <h5>La nature</h5>
      <p>L’action pédagogique d’apprentissage dans et par la nature est dominée par les cycles de celle-ci 
      ainsi que par les propres intérêts de l’enfant.</p>
    </div>
  </div>
</div>