<!-- an Add Event function will be added in the Admin account page. 
The list of events will be created with rows from the database. 
For now, I have created a list. -->

<h2>Evénements à venir :</h2>

<section class="event-list">
  <div class="event-item"> 
    <h5>31 août 2022</h5>
    <p>Journée Portes-Ouvertes</p>
    <p>De 9h00 à 16h00</p>
  </div>
  
  <div class="event-item"> 
    <h5>1 septembre 2022</h5>
    <p>La rentrée scolaire</p>
    <p>Rendez-vous dès 8h30 !</p>
  </div>
  
  <div class="event-item"> 
    <h5>10 septembre 2022</h5>
    <p>La fête de l'école</p>
    <p>Une opportunité de ce rencontrer à la sortie</p>
  </div>
  
  <div class="event-item"> 
    <h5>17 octobre 2022</h5>
    <p>Réunions parents-maître/maîtresse</p>
  </div>
  
  <div class="event-item"> 
    <h5>18 octobre 2022</h5>
    <p>Assemblée Association Parents d'élèves</p>
    <p>Inscription et découverte</p>
  </div>
</section>