<section id="home-event">

<h3>Evénements à venir :</h3>

  <div class="event-item"> 
    <h5>1 septembre 2022</h5>
    <p>La rentrée scolaire.</p>
  </div>
  
  <div class="event-item"> 
    <h5>10 septembre 2022</h5>
    <p>La fête de l'école.</p>
  </div>
  
  <div class="event-item"> 
    <h5>17 octobre 2022</h5>
    <p>Réunions parents-maître/maîtresse.</p>
  </div>
  
  <div class="event-item"> 
    <h5>18 octobre 2022</h5>
    <p>Assemblée Association Parents d'élèves.</p>
  </div>
  


</section>
