<!-- an Add News Item function will be added in the Admin account page. 
The list of articles will be created with rows from the database. 
For now, I have created a list. -->


<div class="news-item"> 
  <div class="news-thumbnail">
    <img src="/Montessori/public/assets/images/portrait/maria_montessori_portrait_hr.jpg" alt="portrait maria montessori">
  </div>
  <div class="news-teaser">
    <h5>Qui était Maria Montessori?</h5>
    <p>Maria Montessori (1870-1952) était docteur en médecine, psychiatre et anthropologue. Elle fut précurseur...</p>
    <a href="https://fr.wikipedia.org/wiki/Maria_Montessori" title="Maria Montessori sur Wiki">Continuer à lire</a>
  </div>
</div>

<div class="news-item"> 
  <div class="news-thumbnail">
    <img src="/Montessori/public/assets/images/courtyard/front_view_children_garden_a_mas_hr.jpg" alt="children in a vegetable garden">
  </div>
  <div class="news-teaser">
    <h5>L'éducation dans et par la nature</h5>
    <p>La nature est un espace d’explorations et d’expériences sans limite, un espace de jeu et d’apprentissage...</p>
    <a href="https://reporterre.net/L-education-a-la-nature-est-primordiale-financons-la" title="Article Reporterre">Continuer à lire</a>
  </div>
</div>

<div class="news-item"> 
  <div class="news-thumbnail">
    <img src="/Montessori/public/assets/images/classroom_student/front_view_teacher_children_music_k_chernaya_hr.jpg" alt="children playing music">
  </div>
  <div class="news-teaser">
    <h5>Notre pédagogie est centrée autour du bien-être de l’enfant</h5>
    <p>L’école alternative les Étoiles représente un lieu où les enfants, les adultes et la nature sont connectés...</p>
    <a href="https://www.reseau-canope.fr/nouveaux-programmes/magazine/vie-scolaire/le-bien-etre-des-enfants-a-lecole-fondements-et-enjeux.html" title="Article Réseau Canopé">Continuer à lire</a>
  </div>
</div>