<section id="home-news">


  <div class="news-item"> 
    <div class="news-thumbnail">
      <img src="/Montessori/public/assets/images/portrait/maria_montessori_portrait.jpg" alt="portrait maria montessori">
    </div>
    <div class="news-caption">
      <h5>Qui était Maria Montessori?</h5>
      <p>Maria Montessori (1870-1952) était docteur en médecine, psychiatre et anthropologue. Elle fut précurseur...</p>
      <a href="">Continuer à lire</a>
    </div>
  </div>
  
  <div class="news-item"> 
    <div class="news-thumbnail">
      <img src="/Montessori/public/assets/images/courtyard/front_view_children_garden_a_mas.jpg" alt="children in a vegetable garden">
    </div>
    <div class="news-caption">
      <h5>L'éducation dans et par la nature</h5>
      <p>La nature est un espace d’explorations et d’expériences sans limite, un espace de jeu et d’apprentissage...</p>
      <a href="">Continuer à lire</a>
    </div>
  </div>
  
  <div class="news-item"> 
    <div class="news-thumbnail">
      <img src="/Montessori/public/assets/images/classroom_student/front_view_teacher_children_music_k_chernaya.jpg" alt="children playing music">
    </div>
    <div class="news-caption">
      <h5>Notre pédagogie est centrée autour du bien-être de l’enfant</h5>
      <p>L’école alternative les Étoiles représente un lieu où les enfants, les adultes et la nature sont connectés...</p>
      <a href="">Continuer à lire</a>
    </div>
  </div>



</section>
