<section>
    <!-- carrousel-->
    <?php include_once "__carousel.phtml"; ?>
    
    <!-- invitation to apply -->
    <?php include_once "__apply.phtml"; ?>    
    
    
    <div class="home-news-events">
        <!-- news -->
        <div class="home-news-section">
            <?php include_once "__news.phtml"; ?>
        </div>
        
        <!-- events -->
        <div class="home-events-section">
            <?php include_once "__event.phtml"; ?>       
        </div>
    </div>
    
    
</section>