<div class="modal-content" id="modal-edit">
      
      <div class="edit-feed-header">
        <h5>Modifier le feed</h5>
       </div>
      
      <div class="edit-feed-body">
            
        <form action="?page=feed_edit" class="edit-feed-form" method="POST" enctype="multipart/form-data">
        <input type="hidden" value="<?php echo $_GET['class-id'] ?>" name="class-id">
        
            <div class="edit-feed-upload-image">
                <div>
                    <label for="upload-image">Télécharger un fichier png|jpeg|jpg : </label>
                    <input type="file" id="upload-image" name="upload-image" accept="image/png, image/jpeg, image/jpg" value="<?php if($feed->getFilePathImage()) echo $feed->getFilePathImage(); ?>">
                </div>
                <div>
                    <label for="upload-image-description" class="edit-feed-upload-image-description">
                        Description de l'image
                        <img style="width:13px; vertical-align:middle" src="/Montessori/public/assets/images/extra/malentendant_pictogramer.png" alt="icon hearing impaired"></img>: 
                    </label>
                    <input type="text" name="upload-image-description" id="upload-image-description" value="<?php if($feed->getImageDescription()) echo $feed->getImageDescription(); ?>"/>
                </div>
            </div>
        
        <div>
            <label for="content" class="edit-feed-content">Description</label>
            <textarea id="content" name="content" rows="5" cols="33"> <?php if($feed->getContent()) echo $feed->getContent(); ?></textarea>
        </div>


        <div>
            <label for="edit-feed-list-students" class="edit-feed-list-students">Qui apparaîsse ? </label>
            <select class="edit-feed-list-select" id="edit-feed-list-students" name="edit-feed-list-students" multiple name="students[]">

                <?php foreach($studentList as $key => $student): ?>
                    <option value="<?php $student->getId(); ?>" <?php if(in_array($student->getId(), $feed->getLinkedStudents())) echo "selected"; ?>> <?php echo $student->getLastname() ." ".$student->getFirstname(); ?> </option>
                <?php endforeach; ?>
                
            </select>
        </div>


        <div>
            <label for="publish-date" class="feed-add-publish-date">Publier?</label>
            <input type="checkbox" name="publish-date" id="publish-date" value="<?php if(!empty($feed->getPublishDate())) echo 'on' ?>">
        </div>
        
      </form>
    
    
    
      </div>
      
      <div class="edit-feed-footer">
        <button type="button" class="edit-form-cancel">Annuler</button>

        <form method="GET">
          <input type="hidden" name="page" value="feed_edit"/>
          <input type="hidden" id="js_feed_edit_id" name="class_feed_id"/>
          <input type="submit" class="btn" id="edit-feed-submit-btn" value="Sauvegarder"/>
        </form>

      </div>
      
    </div>





